### ISSUE TITLE
Not not triggered with empty body

### ISSUE THREAD

**Issue by 0xTim** [tanner0101/release-bot#13]
If the PR body is empty then the bot does not handle that correctly and create a release

**Comment by Kd-Here** [comment]
Can I work for this. I am new to github actions. Hope I will able to resolve the issue and get to learn newthing.

**Comment by 0xTim** [comment]
@Kd-Here go for it! This doesn't actually use GitHub Actions, it runs a Lambda in AWS when the PR is merged that tags it, creates the release in GH and posts in Discord. This repo contains the code for it so have a dig through!
